# Generated by Django 3.2.3 on 2021-05-24 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'criteria',
            },
        ),
        migrations.CreateModel(
            name='Student_Course_Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
        migrations.DeleteModel(
            name='Student_Course_Assigned',
        ),
        migrations.RemoveField(
            model_name='school',
            name='id',
        ),
        migrations.AddField(
            model_name='assignment',
            name='school',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='assignment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.assignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='email_address',
            field=models.CharField(default=0, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='assignment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.assignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email_address',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='student_course_request',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_course_request',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='emails_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student_course_assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AddField(
            model_name='student_course_assignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
