# Generated by Django 3.2.3 on 2021-05-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210524_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_course_assignment',
            options={'verbose_name': 'Student Course Assignment'},
        ),
        migrations.AlterModelOptions(
            name='student_course_request',
            options={'verbose_name': 'Student Course Request'},
        ),
        migrations.AlterField(
            model_name='student',
            name='email_address',
            field=models.CharField(max_length=75),
        ),
    ]
