# Generated by Django 3.2.3 on 2021-05-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210527_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='student_course_request',
            options={'ordering': ['-priority'], 'verbose_name': 'Student Course Request'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(blank=True, to='main.Course'),
        ),
    ]
