# Generated by Django 3.2.3 on 2021-05-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210528_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='course',
            new_name='courses',
        ),
    ]
