# Generated by Django 3.2.3 on 2021-05-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_course_teacher_courses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['full_name']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='deadline',
        ),
        migrations.AddField(
            model_name='assignment',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
