# Generated by Django 3.2.3 on 2021-05-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210528_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='emails_sent',
            new_name='invitation_email_sent',
        ),
        migrations.AddField(
            model_name='assignment',
            name='reminder_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='results_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='results_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
