# Generated by Django 3.2.3 on 2021-06-03 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210528_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.assignment'),
            preserve_default=False,
        ),
    ]
