# Generated by Django 3.2.3 on 2021-06-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_criterion_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterion',
            name='course',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='name',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='max_capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criterion',
            name='all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='criterion',
            name='courses',
            field=models.ManyToManyField(blank=True, to='main.Course'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='students',
            field=models.ManyToManyField(blank=True, to='main.Student'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'needs to have m out of n courses'), (1, 'number of courses'), (2, 'needs to have course x, y, z'), (3, "shouldn't have course x, y, z"), (4, 'max m out of n courses')]),
        ),
    ]
