# Generated by Django 3.2.3 on 2021-06-15 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210603_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Course_Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField()),
                ('assigned', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
            options={
                'verbose_name': 'Student Course Association',
                'ordering': ['-priority'],
            },
        ),
        migrations.RemoveField(
            model_name='student_course_request',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student_course_request',
            name='student',
        ),
        migrations.DeleteModel(
            name='Student_Course_Assignment',
        ),
        migrations.DeleteModel(
            name='Student_Course_Request',
        ),
    ]
