# Generated by Django 3.2.3 on 2021-06-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210615_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_course_association',
            options={'ordering': ['priority'], 'verbose_name': 'Student Course Association'},
        ),
    ]
