# Generated by Django 3.2.3 on 2021-06-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_student_course_association_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='m',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criterion',
            name='n',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_capacity',
            field=models.PositiveSmallIntegerField(default=25),
            preserve_default=False,
        ),
    ]
