# Generated by Django 3.2.3 on 2021-06-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210618_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='reminder_email',
            new_name='invitation_email_message',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='results_email',
            new_name='reminder_email_message',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='invitation_email',
        ),
        migrations.AddField(
            model_name='assignment',
            name='invitation_email_subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='reminder_email_subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='results_email_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='results_email_subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
