# Generated by Django 3.2.3 on 2021-06-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210618_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='invitation_email_subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
