# Generated by Django 3.2.3 on 2021-06-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_assignment_invitation_email_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_course_association',
            options={'ordering': ['-priority'], 'verbose_name': 'Student Course Association'},
        ),
        migrations.AddField(
            model_name='criterion',
            name='name',
            field=models.CharField(default='mjav', max_length=200),
            preserve_default=False,
        ),
    ]
